### ISSUE TITLE
chart-doughnut documentation contains an error

### ISSUE THREAD

**Issue by jibbo** [pkaske/chart-elements#64]
Hi, thanks a lot for your work, I just found out a small error in the documentation: [this](http://robdodson.github.io/chart-elements/components/chart-elements/#chart-doughnut) page indicates that in order to use the doughnut chart you should add the tag with the `values` attribute, like this:

```html
<chart-doughnut values="{{data}}"></chart-doughnut>
```

But it won't work. In fact, it should be:
```html
<chart-doughnut data="{{data}}"></chart-doughnut>
```
Please, mind the attribute, which changed from `values` to `data`. Of course I can fix it and create a pull request if you want, but I thought it was better to let you know first.

**Comment by pkaske** [comment]
Hi @jibbo, one of the maintainers here. You're right, the docs are wrong. A PR would be super welcome if you have time. Thanks for reporting :smiley:
