### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by robdodson** [pkaske/chart-elements#77]
Hey @pkaske I was curious if you'd like me to transfer ownership of this repo over to you? I think you've done a way better job of taking care of it than I ever have, and with the possible move to Lit in #76 it seems like a good time to hand things over. What do you think?

**Comment by pkaske** [comment]
Sure! Makes me even proud to help one of the people who help drive the web platform forward to have more time to do so :)

I guess the only thing left to change after a transfer is to change the configuration for travis, right?

**Comment by robdodson** [comment]
I think so. Let me see if I can initiate the transfer now.

**Comment by robdodson** [comment]
oh it looks like you may need to delete your fork first.

![image](https://user-images.githubusercontent.com/1066253/41381653-9e188a02-6f1d-11e8-9e41-8fcb2c03dfcf.png)

**Comment by pkaske** [comment]
I deleted my fork. But one question. Won't the transfer break installation via bower for current users, because the package path changes? If so, maybe it's better this repo should show a deprecation warning and redirect to a fork of mine?

**Comment by robdodson** [comment]
I think bower just hits GitHub which will redirect to the new owner. Similar to if we renamed the repo.

**Comment by robdodson** [comment]
Let's give it a shot. I can transfer to you and try a bower install. If it blows up then we can transfer back

**Comment by pkaske** [comment]
Sounds good

**Comment by pkaske** [comment]
I've accepted the transfer. It says it takes a few minutes.
