### ISSUE TITLE
Please create a release for the polymer2 branch

### ISSUE THREAD

**Issue by stephanepilla** [pkaske/chart-elements#80]
Hi, 
can you please release the latest polymer2 version ?

We have a polymer2 app where we use the the v4.0.0 version (polymer1) with a few workarounds to make it work with polymer2.
I just saw there is a better way : use your polymer2 version :)

**Comment by pkaske** [comment]
I didn't have much time but I tagged v4.0.1 in the repo. Please try if you can now install it with bower.

**Comment by stephanepilla** [comment]
Thanks, v4.0.1 is now available with bower.
